### PR TITLE
Added add_rosteritem, delete_rosteritem and get_roster commands

### PR DESCRIPTION
**Pull request by encodeltd**
The pull request contains three new commands for roster management.

The following roster management commands are available in Ejabberd's mod_admin_extra module:

add_rosteritem - add an item to user's roster
delete_rosteritem - delete an item from user's roster
get_roster - retrieve user's roster

README contains example usage of the new commands.

Tests passed using modified tox.ini to test the new commands on Ejabberd 15.07 using Python 2.7.9

### CODE REVIEW

**Comment by dirkmoors** [comment]
Hello @encodeltd , thank you for your contribution! I've noticed that the tests are failing though: https://circleci.com/gh/dirkmoors/pyejabberd/159

Could you have a look and provide a fix? I'll merge as soon as we get a green build (with the current tox file ofcourse)

Thanks in advance!

**Comment by encodeltd** [comment]
yep, I am about to test the fix on my dev env. Does the testing ejabberd have mod_admin_extra enabled?

**Comment by dirkmoors** [comment]
Yes, mod_admin_extra and mod_muc_admin are both enabled. The test ejabberd servers are started with the following settings: https://github.com/dirkmoors/pyejabberd/blob/master/ejabberd.sh

**Comment by dirkmoors** [comment]
It seems you're almost there: only the flake8 tests seem to be failing:

```
check runtests: commands[2] | flake8 src
src/pyejabberd/client.py:364:161: E501 line too long (163 > 160 characters)
src/pyejabberd/client.py:396:5: E303 too many blank lines (2)
src/pyejabberd/definitions.py:200:77: W291 trailing whitespace
src/pyejabberd/definitions.py:201:67: W291 trailing whitespace
src/pyejabberd/definitions.py:210:77: W291 trailing whitespace
src/pyejabberd/definitions.py:226:24: E231 missing whitespace after ','
ERROR: InvocationError: '/home/ubuntu/pyejabberd/.tox/check/bin/flake8 src'
```

**Comment by encodeltd** [comment]
yep, just pushed those in, too :-)

**Comment by dirkmoors** [comment]
Awesome, thanks!

**Comment by encodeltd** [comment]
Thank you for the great library! How far away are you from the next release? Asking, because I am going to use the new commands for a project soon.

**Comment by dirkmoors** [comment]
@encodeltd You're welcome, thank you for your contribution! I've made a new release just now, to include your changes: https://pypi.python.org/pypi/pyejabberd/0.2.10

**Comment by encodeltd** [comment]
Marvellous! Cheers

**Pull request merged**
