### PR TITLE
Add connected user info methods

### PR DESCRIPTION
**Pull request by jimcortez**
Add a few API's:
- connected_users
- connected_users_info
- connected_users_number
- user_sessions_info

### CODE REVIEW

**Comment by jimcortez** [comment]
@dirkmoors It seems like the landscape.io link is broken, that seems o be the only issue with the build. I don't quite know what I can do to fix that.

**Comment by dirkmoors** [comment]
@jimcortez You are right...I'm having a lot of problems with @landscapeio url checking lately. I'm going to disable it for now. You can merge master branch, I've added a commit to disable it, and I've implemented various improvements to the test suite (like testing against multiple Ejabberd versions; currently only 15.06, but will add 15.07 and 15.04 in a short while)

**Comment by jimcortez** [comment]
@dirkmoors looks like you added 2.6 support, was that intentional?

**Comment by jimcortez** [comment]
@dirkmoors looks like your new unittest stuff doesn't run properly on 2.6

**Comment by dirkmoors** [comment]
@jimcortez Can you rebase/merge your branch with the master branch? 

If you compare your latest version:
https://github.com/ivee/pyejabberd/blob/master/tests/test_pyejabberd.py#L351

With the one in master:
https://github.com/dirkmoors/pyejabberd/blob/master/tests/test_pyejabberd.py#L355

You'll see the difference. I ran into the same issue, when I activated Python 2.6 support, but I fixed that issue in master.

**Comment by dirkmoors** [comment]
@jimcortez Also, If possible, could you squash your pull request a bit, so we don't have all these commit messages in master?

**Comment by jimcortez** [comment]
Sorry, am a bit new to the whole rebasing thing. If this last merge fixes it, I will squash the rest

**Comment by jimcortez** [comment]
@dirkmoors Things seem to pass now, anything else need to be done?

**Comment by dirkmoors** [comment]
@jimcortez Awesome! I've merged, and I've released: https://pypi.python.org/pypi/pyejabberd/0.2.7
Thank you for contributing!

**Pull request merged**
